### ISSUE TITLE
WiFiManager Generates a Traceback/OSError: [Errno 5] EIO on TinyPico

### ISSUE THREAD

**Issue by wwestrup** [mitchins/micropython-wifimanager#3]
I've tried WiFiManager with with MicroPython builds: 

tinypico-idf3-20191220-v1.12
tinypico-idf3-20200223-v1.12-195-gb16990425

Just running the bare main.py included in WiFiManager-master.

The traceback occurs write after the SSID and password check succeeds. The wifi.dat is not saved.

Errors:
_Connected. Network config:  ('192.168.4.89', '255.255.255.0', '192.168.4.254', '192.168.4.254')
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "wifimgr.py", line 60, in get_connection
  File "wifimgr.py", line 306, in start
  File "wifimgr.py", line 213, in handle_configure
  File "wifimgr.py", line 112, in send_response
  File "wifimgr.py", line 103, in send_header
OSError: [Errno 5] EIO_

**Comment by mitchins** [comment]
Thanks for reporting. Based on the fact ESP-IDF is used is this an ESP32?
EDIT: just saw what the tinyPico is.. pretty neat. Let me fire up the latest build on a regular ESP32 and see what happens

**Comment by wwestrup** [comment]
Thanks! Yes, it's ESP32 based but, actually, I think I reported the bug to the wrong project! There is a similar project that does the same thing, but the main part of the code is in wifimgr.py and includes an example main.py.

I will be trying your version, however, and will report back my findings. 

Thanks, again!

**Comment by wwestrup** [comment]
Your code appears to work just fine on the Tinypico. Sorry for the bother.

**Comment by mitchins** [comment]
Closing as there's no issue. Version 1.0.0 is now released as stable.
